#COMPUTER VISION AND PATTERN RECOGNITION PROJECT 2

Kaan Egemen Sen

In [ ]:
import numpy as np

# World coordinates
X = np.array([
    [-1.0, -1.0, 0.0, 1.0],
    [0.015545, -1.0, 0.965257, 1.0],
    [0.491684, -1.0, 0.965257, 1.0],
    [0.0, 1.03586, 2.1009, 1.0],
    [1.05319, 1.03586, 1.15121, 1.0],
    [1.22323, -1.22323, 0.0, 1.0],
    [0.0, -1.0, 2.1009, 1.0],
    [1.0, 0.234552, 0.489472, 1.0],
    [-1.05319, -1.0, 1.0, 1.0],
    [1.0, 1.0, 0.0, 1.0]
])


# Image Coordinates taken from https://www.mobilefish.com/services/record_mouse_coordinates/record_mouse_coordinates.php
x = np.array([
    [182, 256, 1.0, 1.0],
    [263,166, 1.0, 1.0],
    [306,170, 1.0, 1.0],
    [386,37, 1.0, 1.0],
    [476,133, 1.0, 1.0],
    [363,304, 1.0, 1.0],
    [260,33, 1.0, 1.0],
    [431,210, 1.0, 1.0],
    [175,154, 1.0, 1.0],
    [465,247, 1.0, 1.0]
])

# image coordinates for house2
x2 = np.array([
    [183, 281, 1.0, 1.0],
    [219,182, 1.0, 1.0],
    [239,185, 1.0, 1.0],
    [440,45, 1.0, 1.0],
    [513,158, 1.0, 1.0],
    [246,339, 1.0, 1.0],
    [217,35, 1.0, 1.0],
    [420,247, 1.0, 1.0],
    [180,165, 1.0, 1.0],
    [505,304, 1.0, 1.0]
])

# Constructing the matrix A
A = []
for i in range(len(X)):
    A.append([-X[i][0], -X[i][1], -X[i][2], -X[i][3], 0, 0, 0, 0, x[i][0]*X[i][0], x[i][0]*X[i][1], x[i][0]*X[i][2], x[i][0]*X[i][3]])
    A.append([0, 0, 0, 0, -X[i][0], -X[i][1], -X[i][2], -X[i][3], x[i][1]*X[i][0], x[i][1]*X[i][1], x[i][1]*X[i][2], x[i][1]*X[i][3]])
A = np.array(A)

A2 = []
for i in range(len(X)):
    A2.append([-X[i][0], -X[i][1], -X[i][2], -X[i][3], 0, 0, 0, 0, x2[i][0]*X[i][0], x2[i][0]*X[i][1], x2[i][0]*X[i][2], x2[i][0]*X[i][3]])
    A2.append([0, 0, 0, 0, -X[i][0], -X[i][1], -X[i][2], -X[i][3], x2[i][1]*X[i][0], x2[i][1]*X[i][1], x2[i][1]*X[i][2], x2[i][1]*X[i][3]])
A2 = np.array(A2)

# Performing Singular Value Decomposition (SVD) on A
U, Sigma, Vt = np.linalg.svd(A)
#SVD for 2nd image
U2, Sigma2, Vt2 = np.linalg.svd(A2)

# Obtaining the projection matrix P from the last column of V
P = Vt[-1].reshape(3, 4)
P2 = Vt2[-1].reshape(3, 4)

# Printing the projection matrix P
print("Projection Matrix P:")
print(P)
print( )
print("Projection Matrix P2:")
print(P2)


Projection Matrix P:
[[-1.31489263e-01 -2.07059853e-01  1.42901471e-02 -7.44691027e-01]
 [ 1.13328153e-02 -1.22003426e-02  2.36515043e-01 -5.73450890e-01]
 [ 1.75452219e-04 -2.23343042e-04  5.02675550e-05 -2.28105931e-03]]

Projection Matrix P2:
[[ 2.97526994e-02  2.68752169e-01 -2.90868274e-03  7.01445533e-01]
 [-2.26995340e-02  1.40644271e-02 -2.50269895e-01  6.09508172e-01]
 [-2.31645924e-04  1.19159124e-04 -2.17144396e-06  2.09143462e-03]]


In [ ]:
M=P[:,0:3]
M2=P2[:,0:3]
n=np.array([[0,0,1],[0,1,0],[1,0,0]])
# Perform RQ decomposition
Q, R = np.linalg.qr(M)
Id=np.eye((3))
#Second Image
Q2, R2 = np.linalg.qr(M2)
Id2=np.eye((3))
#Creating identity matrix then multiply with K to make their coordinates Positive
Id[2,2]=-1
R=R@Id
#Second Image
Id2[2,2]=-1
R2=R2@Id2
#Multiply Inverse of Identity matrix with Q to make it coherent
Q=Q@np.linalg.inv(Id)
#Second Image
Q2=Q2@np.linalg.inv(Id2)

#Using The calculation Given in slides to calculate K and R (SLIDE 17 Page 60)
K2=n@R2.T@n
R2=n@Q2.T

K=n@R.T@n
R=n@Q.T

# Normalize K
K /= K[2, 2]

K2 /= K2[2, 2]

# Recover non-homogeneous world coordinates C
C = -R.T @ P[:, -1]

C2 = -R2.T @ P2[:, -1]


print("Camera Calibration Matrix K:")
print(K)

print("\nCamera Orientation R:")
print(R)

print("\nNon-homogeneous World Coordinates C:")
print(C)

print()
print()
print("Camera Calibration Matrix K From second image:")
print(K2)

print("\nCamera Orientation R From Second image:")
print(R2)

print("\nNon-homogeneous World Coordinates C from second image:")
print(C2)


Camera Calibration Matrix K:
[[ 0.02942592  1.79453211 -0.04600955]
 [ 0.          0.22685477  1.5551737 ]
 [ 0.          0.          1.        ]]

Camera Orientation R:
[[ 9.88346052e-05  1.66263766e-02 -9.99861767e-01]
 [-8.58799525e-02 -9.96167634e-01 -1.65734371e-02]
 [-9.96305487e-01  8.58697192e-02  1.32941660e-03]]

Non-homogeneous World Coordinates C:
[-0.05144697 -0.55867583 -0.75408911]


Camera Calibration Matrix K From second image:
[[ 0.06743275  5.36352422 -3.99449274]
 [-0.          4.65485426  5.48130587]
 [-0.         -0.          1.        ]]

Camera Orientation R From Second image:
[[-8.48415577e-05  1.00931525e-02 -9.99949059e-01]
 [-6.06583957e-01 -7.94979458e-01 -7.97279150e-03]
 [-7.95019431e-01  6.06552380e-01  6.18979166e-03]]

Non-homogeneous World Coordinates C from second image:
[0.37144012 0.47619812 0.70625634]
